### ISSUE TITLE
METASPACE 1.6 Deployment checklist

### ISSUE THREAD

**Issue by LachlanStuart** [metaspace2020/metaspace#431]
- [x] Before deployment, ensure the feature flags are set this way:
```
sm_webapp_features:
  coloc: true
  ion_thumbs: true
  off_sample: true
  off_sample_col: false
  new_feature_popups: true
  optical_transform: true
  all_dbs: false
  all_adducts: false
  neutral_losses: false
  neutral_losses_new_ds: true
  chem_mods: false
  advanced_ds_config: false
  isomers: false
```

- [x] After deployment (and after graphql has run its automatic migrations) run:
```
cd /opt/dev/metaspace/metaspace/engine
source activate sm
nice time python -m migrations.r1_5_20190812_ion_formulas
# Should take ~35 minutes
nice time python -m scripts.update_es_index --ds-name "%' order by id desc; --"
# Should take 7 hours
```
